ALTER TABLE Users
DROP CONSTRAINT pk_Users

ALTER TABLE Users
ADD CONSTRAINT pk_Users PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT uq_Username UNIQUE(Username)

ALTER TABLE Users
ADD CONSTRAINT ch_Username CHECK(LEN(Username) >= 3)
