CREATE TABLE Cities
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
[Name] NVARCHAR(20) NOT NULL,
CountryCode CHAR(2) NOT NULL
)

CREATE TABLE Hotels
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
[Name] NVARCHAR(30) NOT NULL,
CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id),
EmployeeCount INT NOT NULL,
BaseRate DECIMAL(15, 2)
)

CREATE TABLE Rooms
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
Price DECIMAL(15, 2) NOT NULL,
[Type] NVARCHAR(20) NOT NULL,
Beds INT NOT NULL,
HotelId INT NOT NULL FOREIGN KEY REFERENCES Hotels(Id)
)

CREATE TABLE Trips
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
RoomId INT NOT NULL FOREIGN KEY REFERENCES Rooms(Id),
BookDate DATE NOT NULL,
ArrivalDate DATE NOT NULL ,
ReturnDate DATE NOT NULL,
CancelDate DATE,
CONSTRAINT CH_BookDate_Before_ArrivalDate CHECK(BookDate < ArrivalDate),
CONSTRAINT CH_ArrivalDate_Before_ReturnDate CHECK(ArrivalDate < ReturnDate)
)

CREATE TABLE Accounts
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(30),
LastName NVARCHAR(50) NOT NULL,
CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id),
BirthDate DATE NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE AccountsTrips
(
AccountId INT NOT NULL CONSTRAINT FK_AccountsTrips_Accounts FOREIGN KEY REFERENCES Accounts(Id),
TripId INT NOT NULL CONSTRAINT FK_AccountsTrips_Trips FOREIGN KEY REFERENCES Trips(Id),
Luggage INT NOT NULL CHECK(Luggage >= 0),
CONSTRAINT PK_AccountsTrips PRIMARY KEY(AccountId, TripId)
)
