CREATE TABLE Clients
(
Id INT NOT NULL IDENTITY CONSTRAINT PK_Clients PRIMARY KEY,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR(30) NOT NULL,
Gender CHAR(1) CONSTRAINT CH_Gender_MorF CHECK(Gender IN('M', 'F')),
BirthDate DATETIME,
CreditCard NVARCHAR(30) NOT NULL,
CardValidity DATETIME,
Email NVARCHAR(50) NOT NULL
)

CREATE TABLE Towns
(
Id INT NOT NULL IDENTITY CONSTRAINT PK_Towns PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Offices
(
Id INT NOT NULL IDENTITY CONSTRAINT PK_Offices PRIMARY KEY,
[Name] NVARCHAR(40),
ParkingPlaces INT,
TownId INT NOT NULL CONSTRAINT FK_Offices_Towns FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Models
(
Id INT NOT NULL IDENTITY CONSTRAINT PK_Models PRIMARY KEY,
Manufacturer NVARCHAR(50) NOT NULL,
Model NVARCHAR(50) NOT NULL,
ProductionYear DATETIME, 
Seats INT,
Class NVARCHAR(10),
Consumption DECIMAL(14, 2)
)

CREATE TABLE Vehicles
(
Id INT NOT NULL IDENTITY CONSTRAINT PK_Vehicles PRIMARY KEY,
ModelId INT NOT NULL CONSTRAINT FK_Vehicles_Models FOREIGN KEY REFERENCES Models(Id),
OfficeId INT NOT NULL CONSTRAINT FK_Vehicles_Offices FOREIGN KEY REFERENCES Offices(Id),
Mileage INT
)

CREATE TABLE Orders
(
Id INT NOT NULL IDENTITY CONSTRAINT PK_Orders PRIMARY KEY,
ClientId INT NOT NULL CONSTRAINT FK_Orders_Clients FOREIGN KEY REFERENCES Clients(Id),
TownId INT NOT NULL CONSTRAINT FK_Orders_Towns FOREIGN KEY REFERENCES Towns(Id),
VehicleId INT NOT NULL CONSTRAINT FK_Orders_Vehicles FOREIGN KEY REFERENCES Vehicles(Id),
CollectionDate DATETIME NOT NULL, 
CollectionOfficeId INT NOT NULL CONSTRAINT FK_Orders_Offices_Collection FOREIGN KEY REFERENCES Offices(Id),
ReturnDate DATETIME,
ReturnOfficeId INT CONSTRAINT FK_Orders_Offices_Return FOREIGN KEY REFERENCES Offices(Id),
Bill DECIMAL(14, 2),
TotalMileage INT
)
