CREATE DATABASE OnlineStore

--In Judge must be pasted without this above

CREATE TABLE ItemTypes
(
ItemTypeID INT NOT NULL CONSTRAINT PK_ItemTypes PRIMARY KEY,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items
(
ItemID INT NOT NULL CONSTRAINT PK_Items PRIMARY KEY,
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT NOT NULL CONSTRAINT FK_Items_ItemTypes FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Cities
(
CityID INT NOT NULL CONSTRAINT PK_Cities PRIMARY KEY,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
CustomerID INT NOT NULL CONSTRAINT PK_Customers PRIMARY KEY,
[Name] VARCHAR(50) NOT NULL,
Birthday DATE NOT NULL,
CityID INT NOT NULL CONSTRAINT FK_Customers_Cities FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders
(
OrderID INT NOT NULL CONSTRAINT PK_Orders PRIMARY KEY,
CustomerID INT NOT NULL CONSTRAINT FK_Orders_Customers FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems
(
OrderID INT NOT NULL,
ItemID INT NOT NULL,
CONSTRAINT PK_OrderItems PRIMARY KEY(OrderID, ItemID),
CONSTRAINT FK_OrderItems_Orders FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
CONSTRAINT FK_OrderItems_Items FOREIGN KEY(ItemID) REFERENCES Items(ItemID)
)
